### ISSUE TITLE
make compile fail (CPU.bsv line 319)

### ISSUE THREAD

**Issue by michalmonday** [bluespec/Flute#40]
Hello, when I use `make compile` in various build directories, it results in:

```
Error: "../../src_Core/CPU/CPU.bsv", line 319, column 37: (T0020)
  Type error at:
    rg_pc_reported

  Expected type:
    ISA_Decls::WordXL

  Inferred type:
    Bit#(64)
```

It looks like there was a recent change to that part:
https://github.com/bluespec/Flute/commit/bbee1f3f5bc37cbcb66771a646e34edbf18dce63#diff-466f63b34521ac100a07ab1b0d97102bb96e2ba7658806fc0ad558b9ef49adf1

Could it be the reason?

**Comment by rsnikhil** [comment]
Yes, you are correct.  I have fixed the bug (commit d7235cf9).
Thank you for reporting it.
