### ISSUE TITLE
Where Can I get the Bluespec systemverilog compiler?

### ISSUE THREAD

**Issue by hyf6661669** [bluespec/Flute#9]
I have already looked at www.bluespec.com and your forum http://forum.bluespec.com/viewtopic.php?t=651&sid=d5e77b8d702f34485d0167e06d877261. I also sent an email to support@bluespec.com but I got no useful response. Can you give me a link to download the bsc?

Thanks!

**Comment by charlie-bluespec** [comment]
Please resubmit your request and return email to  support@bluespec.com

---------- Forwarded message ---------
